### PR TITLE
Check for the local Release directory if we don't have one for Build.

### PR DESCRIPTION
**Pull request by FunnyFry**
Proposed fix to address open issue of the **NuGet Publisher** task not working when ran from within a Release Definition: #745.

### CODE REVIEW

**Comment by pascalberger** [comment]
:+1: for being able to use NuGet Publisher in release definitions

**Comment by GitHubSriramB** [comment]
Instead of relying on AGENT_BUILDDIRECTORY/AGENT_RELEASEDIRECTORY, suggest using SYSTEM_DEFAULTWORKINGDIRECTORY which gets set to appropriate value within Build/Release.

**Comment by FunnyFry** [comment]
Hi @GitHubSriramB. I have thought of using ```SYSTEM_DEFAULTWORKINGDIRECTORY``` also. Except when using this parameter during the build it is set as ```[agent root]\_work\#\s``` which is where the source is downloaded. I do not think that temporary data should be created within the source location.

Perhaps the value of ```SYSTEM_DEFAULTWORKINGDIRECTORY``` is being set incorrectly. I would think the working directory should be the same as ```AGENT_BUILDDIRECTORY``` (```[agent root]\_work\#```).

**Comment by bryanmacfarlane** [comment]
>> Perhaps the value of SYSTEM_DEFAULTWORKINGDIRECTORY is being set incorrectly. I would think the working directory should be the same as AGENT_BUILDDIRECTORY ([agent root]\_work\#).

No, that's not correct.

https://msdn.microsoft.com/Library/vs/alm/Build/scripts/variables 

System.DefaultWorkingDirectory
SYSTEM_DEFAULTWORKINGDIRECTORY
The default working directory for this job. In Build this is **Build.SourcesDirectory**. In Release this is Release.ArtifactsDirectory

**Comment by bryanmacfarlane** [comment]
assigning to chrispatterson who defined that - he can clarify

**Comment by mxa0079** [comment]
Any updates on this?

**Comment by omeshp** [comment]
I think what we want is system.artifactsdirectory which should point to AGENT_BUILDDIRECTORY for build and AGENT_RELEASEDIRECTORY in case of Release.

**Comment by vtbassmatt** [comment]
PR #1034 addressed this. Closing.

**Pull request closed without merging**
