### PR TITLE
Users/ajya/wfc password with special character

### PR DESCRIPTION
**Pull request by Ajay-MS**

### CODE REVIEW

**Comment by pavanadepu2** [comment]
Looks fine.

**Comment by kmkumaran** [comment]
Looks fine. Are there any other task instances with similar issue?

**Comment by Ajay-MS** [comment]
Yes there are some more instance IISWebAppDeployment,AzureFileCopy and SqlServerDacpac .

**Comment by kmkumaran** [comment]
Can we address in other relevant places as well.

**Comment by Ajay-MS** [comment]
Will change at relevant places at part of different PR.

**Pull request merged**
