### PR TITLE
add an Install mode to NuGetInstaller

### PR DESCRIPTION
**Pull request by vtbassmatt**
address #1282 by adding a mode switch - restore by default, install if you need it

### CODE REVIEW

**Comment by NenoLoje** [comment]
Thanks, Matt!

I checked on the [nuget.exe docs](https://docs.nuget.org/consume/command-line-reference#install-command-usage). There are two ways to use the *install* command.

- Usage 1: `nuget install packageId`
- Usage 2: `nuget install pathToPackagesConfig`

I think we do support the second case, but do we also support the first one (or what would it take to make that happen)?

**Comment by NenoLoje** [comment]
As an example, here's how a typical nuget.exe install command looks like in a build process:

`nuget.exe install BuildScripts -Source %NuGetFeedUrl% -ExcludeVersion -NonInteractive -Verbosity detailed -OutputDirectory %Build.BinariesDirectory%`

**Comment by vtbassmatt** [comment]
I debated whether to explicitly support usage 1 or not. As implemented, it will work -- I couldn't find a nice way to write about it in the strings, though :) Open to thoughts.

-ExcludeVersion used to be a checkbox, but it was removed and I don't know why.

**Comment by vtbassmatt** [comment]
Oh, also, I don't want to change the name of the arguments because I'm not sure of the back-compat implications. End users won't see that.

**Comment by NenoLoje** [comment]
Looks good to me.

Is there any easy way I could test this on a VSTS account, if it works as expected?

- Not sure why the ExcludeVersion checkbox got removed, but I guess it's fine as one can specify any additional arguments.
- OK for not changing name of arguments; not sure of the impact on back-compat ether.

**Comment by vtbassmatt** [comment]
To test on VSTS:

- Clone this repo: `git clone https://github.com/Microsoft/vso-agent-tasks`
- Install [tfx-cli](https://www.npmjs.com/package/tfx-cli)
- Get a [PAT](http://blog.devmatter.com/personal-access-tokens-vsts/) for your account
- `tfx login --service-url https://{ACCOUNT}.visualstudio.com/DefaultCollection --token {PAT}`
- cd into `vso-agent-tasks\Tasks\NugetInstaller`
- `tfx build tasks upload --task-path . --overwrite`

**Comment by NenoLoje** [comment]
Thanks, Mat. I could import it successfully.

I tested it by creating a new build definition from the Visual Studio template, where the NuGet Installer task is used, and noticed that none of the two radio buttons ("restore" and "install") was checked. Should we show one as checked by default?

**Comment by NenoLoje** [comment]
Also, not sure: how would I got if I would want to do the "usage 1" scenario from above? Would I leave the _path to solution_ as well as _nuget.config_ arguments empty, and just use the additional arguments?

**Comment by vtbassmatt** [comment]
Ah, a typo in my task.json caused it not to default. Could you pull, reupload, and add the task again? (It probably won't automatically update your existing instance of the task.)

For usage 1, you _could _ just type the name of the package where it asks for the solution file. Though now that you make me type that out, it doesn't sound so nice :-1: Also, leaving the solution field blank will cause the task to fail -- that's existing behavior that I don't want to change.

In general we want to drive customers towards configuration & environment setup that lives with the code, rather than idiosyncratic things you do only in CI. For that reason, I'm OK with making usage 2 the common case. If you really, really want usage 1, you have other options.

**Comment by NenoLoje** [comment]
The default works es expected now ([x] restore is checked). Regardless of what we come up for usage 1, I think this would already make an good merge.

Regarding usage 1:I tried to put in a NuGet Package name for solution file, however it came out as a folder path instead.

Example: here's what comes out when I enter `BuildScripts`

`NuGet.exe install "C:\agent\_work\48\s\BuildScripts`

Generally I agree that config as a code is a good practice. Let me back up a bit and explain the scenario I'm having in mind. As somebody who runs the TFS Build infrastructure at a company, I have a set of build helpers (scripts, tools, etc.) that I want to re-use in many build definitions. Adding those tools to the packages.config files of all projects/solutions, doesn't sound like the best approach in this case. There are multiple ways how one could solve this.

Right now, I would run `nuget.exe install BuildScripts -source` and point it to a special NuGet Feed URL that only contains those build infrastrcture artifacts. The _NuGet restore_ for the actual project dependencies will be done later - which is the most common use case for the NuGet installer task.

The primary reason why I would prefer to use the NuGet installer task over invoking nuget.exe manually is that I have to use PATs to access VSTS' package management feeds.

What are your thoughts. Does the scenario above sound valid?

**Comment by vtbassmatt** [comment]
Too bad about the file path -- I guess because it's defined as a file path in task.json, the runner is automatically prepending it.

Your scenario makes sense to me, and I agree it's the right way to do things. I'll think about that some more.

**Comment by NenoLoje** [comment]
Me, too. :) Thanks for considering, Matt!

**Comment by NenoLoje** [comment]
Nevertheless I think the PR is good as it is for now.

**Comment by vtbassmatt** [comment]
Thanks! I need to make sure I haven't broken anything, and then I'll pull this in.

For the build tools scenario, what I should probably do is create a "single package installer" task (terrible name, but you get the idea). Before I can do that, I need to factor out the VsoCredential stuff into a common library. Before I can do _that_, I need to get some tests in place. So -- it's on my backlog but may not happen for a while.

To unblock your scenario: Take a look at how we implemented the auth stuff in this task. That infrastructure is all availble to you, so you could write your own custom task.

**Comment by NenoLoje** [comment]
Yes, I get the idea. :) The "single package installer" task is probably exactly what I was looking for for this scenario. Thanks, Matt! :)

**Pull request merged**
