### PR TITLE
added uri and sasToken as optional outputs

### PR DESCRIPTION
**Pull request by bmoore-msft**
when files are copied, it's likely other tasks in the work flow need to know where they were copied to and have secure access to them.  Using outputs of the container and sasToken will enable this.  The outputs are only available if the target a blob (not vm) and the vars are provided.

### CODE REVIEW

**Comment by kmkumaran** [comment]
1) Can you do gulp and include the task.loc file as part of your commit.
2) Can you also update the Readme.md file to reflect the output variable section.

**Comment by bmoore-msft** [comment]
@kmkumaran - updated tasks.loc & readme.md
@pavanadepu2 - yes that cmdlet works with AzureRM storage (storage team didn't rename all the cmdlets like most did)

**Comment by kmkumaran** [comment]
Looks fine.

**Comment by kmkumaran** [comment]
This was merged as part of different PR. Closing this PR.

**Pull request closed without merging**
