### PR TITLE
update commands

### PR DESCRIPTION
**Pull request by yaananth**

### CODE REVIEW

**Comment by pascalberger** [comment]
Could you please also fill in the "Minimum Agent Version" for having documented with which version the new command is available / old deprecated.

**Comment by yaananth** [comment]
Well it's not the agent here, it's the server that renders uploaded data in UI. So, though the command works ( it uploads the data ), after next sprint deployment the data won't be shown in UI.

**Comment by pascalberger** [comment]
The problem is that if you write custom tasks you'll have no clue which commands are available on VSTS or a certain On-Prem version (and I assume this documentation is for writing custom tasks). For you it's clear that this will change with next sprint, but from an outside point of view it's even hard to find out when a certain sprint was deployed. Even if it is not dependent on the agent, agent version is the easiest way to find out deployed sprint. I already discussed this problem with @bryanmacfarlane on other issues.

**Comment by yaananth** [comment]
@pascalberger This particular command allows adding summary markdown to completed build. This is not about writing custom tasks. I agree that it's unclear on sprint deployments ( atleast as far as I know ). Problem with using agent version here is that, agent versions before that minimum doesn't work since it's dependent on TFS server. So it's better not to include agent version in this particular case since, whatever the agent version is, it's the server that renders the UI.

**Pull request merged**
