### PR TITLE
CsPkg, CsCfg & package task fields input are essentially artifact fil…

### PR DESCRIPTION
**Pull request by pagarwal-msft**
CsPkg, CsCfg & package task fields input are essentially artifact file paths.
We have task input type of filePath which maps to source repo. Adding a new task input type of artifactPath - which will be mapped to artifact file paths.

### CODE REVIEW

**Comment by ankitgo** [comment]
looks good

**Comment by kmkumaran** [comment]
Looks fine.

**Comment by bryanmacfarlane** [comment]
not sure this will work.  This will make it unusable in build right?

**Comment by bryanmacfarlane** [comment]
>> We have task input type of filePath which maps to source repo

This is not the case and not the intent of the original design.  We called it filePath (generic) and not sourcePath intentionally.  It means that filePath is supposed to be interpreted in context of it's use.  So in build where we're browsing for files in a repo filePath means in context of the repo.  In a release definition filePath is in context of artifacts the release process is using.

**Pull request closed without merging**
