### PR TITLE
Generic npm runner

### PR DESCRIPTION
**Pull request by pascalberger**
This adds a new task for running (any) npm task. It adds a demand for npm being installed on the agent, and takes care of finding npm and parses any warning messages.

### CODE REVIEW

**Comment by chrisrpatterson** [comment]
I would prefer that we simply update the existing NPM task to add an input that takes the command to run and have the default value of that be install.  You should also in the script treat empty as install.

Thanks for all your help.

**Comment by pascalberger** [comment]
OK, will update PR. @chrisrpatterson Do you want to keep the npm install task to keep its name (npm install), which might be confusing or should I update it to npm runner (or something else?

**Comment by chrisrpatterson** [comment]
You can rename the task with no issues to NpmRunner.  As long as the Guid stays the same everything will update nicely.

**Comment by pascalberger** [comment]
@chrisrpatterson Changed to enhance the existing npm install task with a command field.

**Comment by bryanmacfarlane** [comment]
@pascalberger can we just rename it "Npm"  - runner is redundanct - all of our tasks are runners and we don't do this for other tasks.

**Comment by pascalberger** [comment]
@bryanmacfarlane Sure, renamed it to only npm

**Comment by pascalberger** [comment]
@bryanmacfarlane @chrisrpatterson Is it OK like this? Any chance to have this merged?

**Pull request merged**
