### PR TITLE
Sql Azure task profile fix

### PR DESCRIPTION
**Pull request by mvvsubbu**

### CODE REVIEW

**Comment by kmkumaran** [comment]
Looks fine.

**Comment by anaggar** [comment]
Fine

**Comment by Ajay-MS** [comment]
Looks fine

**Comment by 2572** [comment]
@mvvsubbumvvsubbu merged commit 35f4874 into releases/m96 an hour ago

**Comment by 2572** [comment]
framus-5-98-guitar-1

**Pull request merged**
