### PR TITLE
Added PatchAssemblyInfoVersions task

### PR DESCRIPTION
**Pull request by z4kn4fein**
A new task which can be used to upgrade the AssemblyVersion, AssemblyFileVersion and AssemblyInformationalVersion attributes in AssemblyInfo files.

### CODE REVIEW

**Comment by chrisrpatterson** [comment]
Thank you for the PR. However, I am not 100% sure I want this one in the box yet.  At the moment we don't have a good version management story and I would like to build that feature before we offer an OOB solution to customers.

We will soon offer and extension gallery for VSO and you will have the option publishing build tasks to that for people to consume.  I think that would be a good option for this and potentially related tasks.

If you are interested I would be happy to get you the information as soon as we are ready.

**Comment by z4kn4fein** [comment]
Sure, i'm really interested and i would be greatful if you could notify me when that'll happen. Shall i close my other PR too and try to publish it via VSO extension gallery as well, or can i leave it open for review? It's about cloud service swapping, not related to version management.

Thanks for the feedback.

**Comment by jorrit** [comment]
@z4kn4fein perhaps you can publish this task in an github repository of your own? In that way improvements can be more easily contributed and downloaded.

**Comment by z4kn4fein** [comment]
@jorrit sure, i've created a [new repo](https://github.com/z4kn4fein/vsts-build-tasks) for my tasks, feel free to contribute.

**Comment by bryanmacfarlane** [comment]
closing since you created a repo

**Pull request closed without merging**
