### PR TITLE
Missing DTL Import DLL in DTA Task for Register-Environment

### PR DESCRIPTION
**Pull request by nigurr**
Issue: Missing DTL Import DLL in DTA Task for Register-Environment cmdlet.
Fix: Importing the DTL dll explicitly in DTA Task

### CODE REVIEW

**Comment by nigurr** [comment]
Internal tracking details: 531337

**Comment by kaadhina** [comment]
Add validation details. Looks good.

**Comment by nigurr** [comment]
Manual testing done and verified the fix.

**Comment by acesiddhu** [comment]
looks fine

**Pull request merged**
