### PR TITLE
Removing SCVMM Task .

### PR DESCRIPTION
**Pull request by chshrikh**
Removing the SCVMM task . It will be developed with its own git hub repo

### CODE REVIEW

**Comment by kmkumaran** [comment]
Looks fine.

**Comment by ChristophLindemann** [comment]
What repo is this task moved to?

**Comment by chshrikh** [comment]
@ChristophLindemann  the repo is private. The task is available with extension - https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.scvmmapp

**Comment by ChristophLindemann** [comment]
@chshrikh I was just wondering where I would go if I have some input or questions about the task.

As I felt like the `User Review` on https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.scvmmapp, might be the wrong place for such discussions.

**Pull request merged**
