### PR TITLE
NuGetInstaller: Add UI for defining NuGet package sources

### PR DESCRIPTION
**Pull request by pascalberger**
Adds UI to define custom NuGet sources for package restore in the NuGetInstaller task.

### CODE REVIEW

**Comment by pascalberger** [comment]
Should I also commit the updated task.loc.json file?

**Comment by chrisrpatterson** [comment]
Yes you should also commit that file.

**Comment by pascalberger** [comment]
@chrisrpatterson Any chance to get this merged or should I close the PR?

**Comment by bryanmacfarlane** [comment]
Matt, can you have a look?

**Comment by vtbassmatt** [comment]
I don't think this PR makes sense with our current direction. We prefer folks use nuget.config to define sources, that way it works on both dev machines and in CI. I'm open to adding UI as an alternate for people where it makes sense, but we'd also need a way to tag them with credentials.

**Pull request closed without merging**
