### PR TITLE
Added Cake task.

### PR DESCRIPTION
**Pull request by patriksvensson**
Hello,

I'm not sure if you accept pull requests for new tools, but here is a new task for running Cake scripts.

http://cakebuild.net
https://github.com/cake-build/cake

##### 1. Create build script

Create a `build.cake` file in your repository.

```csharp
var target = Argument("target", "Default");

Task("Build")
  .Does(() =>
{
  MSBuild("./src/MyProject");
});

Task("Default")
  .IsDependentOn("Build");

RunTarget(target);
```

##### 2. Add build step

cake-vso

### CODE REVIEW

**Comment by bryanmacfarlane** [comment]
Thanks for writing the cake task!  This repro contains tasks that end up in the box in VSO.  We have an a new extensions gallery where users can contribute tasks and the community can find on a gallery.  Follow up with me (bryanmac) and chrispat both at microsoft dot com

**Comment by patriksvensson** [comment]
@bryanmacfarlane Done

**Comment by devlead** [comment]
@bryanmacfarlane sounds interesting, when will info about this extension gallery be public?

You should update [README.md/Contributing](https://github.com/Microsoft/vso-agent-tasks#contributing) with this info, best would be if you added an [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) as those are displayed on GitHub when you create a pull request or issue. 

Would be excellent if the extension gallery offers a seamless experience, have 1500+ projects using Cake Build scripts at different customers would have been nice to easily use the vNext build system for this.

**Comment by bryanmacfarlane** [comment]
I will update contributing when it's in public preview.  Following up offline with you ...

**Comment by devlead** [comment]
@bryanmacfarlane ok, thanks for the quick reply! :+1:

**Pull request closed without merging**
