### PR TITLE
Fixing issue #788 where resourceGroup was not passed into environment…

### PR DESCRIPTION
**Pull request by hrboyceiii**
…Name or set to the value of the output variable

### CODE REVIEW

**Comment by KrishnaAdityaB** [comment]
Hey hrboyceiii,
current could should answer issue #788.
This PR will break the scenario where - you created an Azure Resource Group with name "azureRGName" and save it as an output variable with name "outputEnvName". You want to use it in PowerShellOnTargetMachines task by referring to it as "$(outputEnvName)".

What is the exact problem you are trying to solve?

**Comment by hrboyceiii** [comment]
Right now, if I specify an value for output variable, the task fails on Register-Environment in Utility.ps1 (line 383, see attached log file).  My understanding is that $outputVariable will store the machines from the resource group which I can then pass into subsequent tasks, like PowerShell on Target or Visual Studio Test Agent deployment.

Either way, when I use this task today using a hosted agent with the a value specified for output variable, it fails with the attached error.  The fix in the PR makes Register-Environment work.

How should these tasks be used??  Including @pryenugu who's helping with a similar issue (#969) with the Test Agent Deployment task.
[tasklog_2.txt](https://github.com/Microsoft/vso-agent-tasks/files/59534/tasklog_2.txt)

**Comment by KrishnaAdityaB** [comment]
@hrboyceiii 
These tasks have a dependency on latest agent while using Register-Environment.
But hosted agents are not yet updated - should be updated sometime this week.
That is the reason for the failure message you are facing. Though the code changes you sent in PR fix the error message - they doesn't fix the functionality.
Thank you for the contribution.

I will get back to you once the hosted agent upgrade is done. Until then can you try with a private agent?

And regarding issue #969 - Deploy test agent task doesn't yet support consuming machine groups output by another task.

**Comment by KrishnaAdityaB** [comment]
@hrboyceiii  hosted agents were upgraded last week.

**Pull request closed without merging**
