### PR TITLE
The following changes are included

### PR DESCRIPTION
**Pull request by mvvsubbu**
1. Build summary not showing proper name for our tasks.
2. Extra white spaces got added in loc.json
3. Few missing checkins for PerformActionOnMachineGroup

### CODE REVIEW

**Comment by pankagar13** [comment]
Signing off for   PerformActionOnMachineGroup task

**Comment by allendm-msft** [comment]
Looks OK

**Comment by AnubhavAggarwal** [comment]
looks fine

**Comment by acesiddhu** [comment]
are these for M83 as well?

**Pull request merged**
