### PR TITLE
Fixed NuGetPublisher spaces in package path

### PR DESCRIPTION
**Pull request by VaticanUK**
Fixed NuGetPublisher to allow it to upload packages which contain spaces
within the path

### CODE REVIEW

**Comment by ericsciple** [comment]
Looping in Emanuel to take a look.

**Comment by VaticanUK** [comment]
Anything I can do to help get this merged? I need this fix so I'm having to use this task from my branch at the moment rather than the Microsoft one :(

**Comment by bryanmacfarlane** [comment]
I pinged a couple folks ... hopefully should hear soon

**Comment by REscobar** [comment]
I ran into this issue yesterday, and checked trough the issues and there were none, forgot to check the pending pull requests before creating the issue #875, btw, shouldn't the version be bumped by one also in this pr?

**Comment by pascalberger** [comment]
@ericsciple @bryanmacfarlane Any chance to have this merged?

**Comment by ericsciple** [comment]
Corrected the assignee (assigned to Matt).

**Comment by vtbassmatt** [comment]
@VaticanUK in the other NuGet tasks, we've used the backtick form of escaping quotes: https://github.com/Microsoft/vso-agent-tasks/commit/f7c7f439e946a448437b230149a38170491f3c46  Could you update your PR with that format and then I'll accept? Thanks.

**Comment by VaticanUK** [comment]
Done

**Comment by vtbassmatt** [comment]
Thanks!

**Pull request merged**
