### PR TITLE
Added a DeploymentLabel parameter to Publish-AzureCloudDeployment.ps1

### PR DESCRIPTION
**Pull request by phenixdotnet**
Added a DeploymentLabel parameter to allow user to set the deployment label in cloud service

### CODE REVIEW

**Comment by phenixdotnet** [comment]
Hi.

Any update about this PR ? 

Thanks.

**Comment by chrisrpatterson** [comment]
@phenixdotnet If a user leaves the label empty is specifying -Label as an empty string on the cmdlet going to cause any issues?

**Comment by phenixdotnet** [comment]
@chrisrpatterson : Yes if you leave the label empty but try to use the -Label option you get an error in powershell, somethings like that "Unable to to validate the argument -Label, argument is null or empty".

**Comment by bryanmacfarlane** [comment]
This is not relevant this sprint because it was rewritten task.  n  Can you have a look at the new implementation phenixdotnet ?

**Pull request closed without merging**
