### PR TITLE
Fix typo in variable name

### PR DESCRIPTION
**Pull request by pascalberger**
Fixes a typo in variable names

### CODE REVIEW

**Comment by pascalberger** [comment]
@kmkumaran Any chance to have this and #696 merged?

**Comment by bryanmacfarlane** [comment]
adding Allen - I think Muthu is out till 11/11

**Comment by allendm-msft** [comment]
Signed off on changes.

**Comment by mvvsubbu** [comment]
Please update task Patch version as well.

**Comment by mvvsubbu** [comment]
Patch version i will update. I am committing this changes

**Pull request merged**
